apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
  annotations:
    kompose.cmd: kompose --file ../backend/docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
spec:
  type: NodePort
  selector:
    io.kompose.service: backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30719
