apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    io.kompose.service: frontend
  annotations:
    kompose.cmd: kompose --file ../frontend/docker-compose.yml convert
    kompose.version: 1.36.0 (ae2a39403)
spec:
  type: NodePort
  selector:
    io.kompose.service: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30718
